apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-shakespeare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-shakespeare
  template:
    metadata:
      labels:
        app: pokemon-shakespeare
    spec:
      containers:
        - name: pokemon-shakespeare
          image: pokemon-shakespeare
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-shakespeare-service
spec:
  type: NodePort
  selector:
    app: pokemon-shakespeare
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
