apiVersion: v1
kind: Service
metadata:
  name: pokemon-shakespeare-service
spec:
  selector:
    app: pokemon-shakespeare
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
